server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: vm-auth
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.22.18:3306/vm
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        dialect.storage_engine: innodb

bezkoder:
  app:
    jwtSecret: "======================BezKoder=Spring==========================="
    jwtExpirationMs: 300000
